2025-01-11 13:20:47 UTC
macOS-14.6-arm64-arm-64bit
Ren'Py 8.3.4.24120703

Early init took 0.03s
Loading error handling took 0.07s
Loading script took 0.60s
Loading save slot metadata took 0.01s
Loading persistent took 0.00s
Running init code took 0.09s
Loading analysis data took 0.01s
Analyze and compile ATL took 0.00s
Reloading save slot metadata took 0.00s
Index archives took 0.00s
Backing up script files to '/Users/rayansoussi/Library/RenPy/backups/JustAnotherNight':
Dump and make backups took 0.03s
Cleaning cache took 0.00s
Making clean stores took 0.00s
Initial gc took 0.02s
DPI scale factor: 1.000000
Creating interface object took 0.00s
Cleaning stores took 0.00s
Init translation took 0.02s
Build styles took 0.00s
Load screen analysis took 0.00s
Analyze screens took 0.01s
Save screen analysis took 0.01s
Prepare screens took 0.03s
Save pyanalysis. took 0.00s
Save bytecode. took 0.02s
Running _start took 0.00s
Interface start took 0.19s

Initializing gl2 renderer:
primary display bounds: (0, 0, 1512, 982)
swap interval: 1 frames
Windowed mode.
Vendor: "b'Apple'"
Renderer: b'Apple M1 Pro'
Version: b'2.1 Metal - 88.1'
Display Info: None
Screen sizes: virtual=(1920, 1080) physical=(1410, 793) drawable=(2820, 1586)
Maximum texture size: 4096x4096
Cleaning stores took 0.00s
Init translation took 0.00s
Build styles took 0.00s
Load screen analysis took 0.02s
Analyze screens took 0.00s
Prepare screens took 0.00s
Running _start took 0.00s

Full traceback:
  File "/Users/rayansoussi/Desktop/renpy-8.3.4-sdk/renpy/bootstrap.py", line 359, in bootstrap
    renpy.main.main()
  File "/Users/rayansoussi/Desktop/renpy-8.3.4-sdk/renpy/main.py", line 666, in main
    renpy.persistent.update(True)
  File "/Users/rayansoussi/Desktop/renpy-8.3.4-sdk/renpy/persistent.py", line 434, in update
    save()
  File "/Users/rayansoussi/Desktop/renpy-8.3.4-sdk/renpy/persistent.py", line 456, in save
    renpy.loadsave.location.save_persistent(compressed)
  File "/Users/rayansoussi/Desktop/renpy-8.3.4-sdk/renpy/savelocation.py", line 622, in save_persistent
    l.save_persistent(data)
  File "/Users/rayansoussi/Desktop/renpy-8.3.4-sdk/renpy/savelocation.py", line 426, in save_persistent
    with open(fn_tmp, "wb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/rayansoussi/Desktop/renpy-8.3.4-sdk/JustAnotherNight/game/saves/persistent.1736601646.tmp'

While running game code:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/rayansoussi/Desktop/renpy-8.3.4-sdk/JustAnotherNight/game/saves/persistent.1736601646.tmp'
Traceback (most recent call last):
  File "/Users/rayansoussi/Desktop/renpy-8.3.4-sdk/renpy/main.py", line 652, in main
    run(restart)
  File "/Users/rayansoussi/Desktop/renpy-8.3.4-sdk/renpy/main.py", line 148, in run
    renpy.execution.run_context(True)
  File "/Users/rayansoussi/Desktop/renpy-8.3.4-sdk/renpy/execution.py", line 958, in run_context
    context.run()
  File "/Users/rayansoussi/Desktop/renpy-8.3.4-sdk/renpy/execution.py", line 599, in run
    node.execute()
  File "/Users/rayansoussi/Desktop/renpy-8.3.4-sdk/renpy/ast.py", line 827, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/Users/rayansoussi/Desktop/renpy-8.3.4-sdk/renpy/python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "renpy/common/00start.rpy", line 281, in <module>
    renpy.call_in_new_context(_restart[2])
  File "/Users/rayansoussi/Desktop/renpy-8.3.4-sdk/renpy/game.py", line 377, in call_in_new_context
    return renpy.execution.run_context(False)
  File "/Users/rayansoussi/Desktop/renpy-8.3.4-sdk/renpy/execution.py", line 958, in run_context
    context.run()
  File "/Users/rayansoussi/Desktop/renpy-8.3.4-sdk/renpy/execution.py", line 599, in run
    node.execute()
  File "/Users/rayansoussi/Desktop/renpy-8.3.4-sdk/renpy/ast.py", line 827, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/Users/rayansoussi/Desktop/renpy-8.3.4-sdk/renpy/python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "renpy/common/_layout/screen_main_menu.rpym", line 28, in <module>
    python hide:
  File "renpy/common/_layout/screen_main_menu.rpym", line 35, in _execute_python_hide
    ui.interact()
  File "/Users/rayansoussi/Desktop/renpy-8.3.4-sdk/renpy/ui.py", line 301, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "/Users/rayansoussi/Desktop/renpy-8.3.4-sdk/renpy/display/core.py", line 2215, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "/Users/rayansoussi/Desktop/renpy-8.3.4-sdk/renpy/display/core.py", line 3286, in interact_core
    rv = root_widget.event(ev, x, y, 0)
  File "/Users/rayansoussi/Desktop/renpy-8.3.4-sdk/renpy/display/layout.py", line 1297, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "/Users/rayansoussi/Desktop/renpy-8.3.4-sdk/renpy/display/layout.py", line 1297, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "/Users/rayansoussi/Desktop/renpy-8.3.4-sdk/renpy/display/layout.py", line 1297, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "/Users/rayansoussi/Desktop/renpy-8.3.4-sdk/renpy/display/screen.py", line 791, in event
    rv = self.child.event(ev, x, y, st)
  File "/Users/rayansoussi/Desktop/renpy-8.3.4-sdk/renpy/display/layout.py", line 1297, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "/Users/rayansoussi/Desktop/renpy-8.3.4-sdk/renpy/display/layout.py", line 1297, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "/Users/rayansoussi/Desktop/renpy-8.3.4-sdk/renpy/display/behavior.py", line 1182, in event
    return handle_click(self.clicked)
  File "/Users/rayansoussi/Desktop/renpy-8.3.4-sdk/renpy/display/behavior.py", line 1103, in handle_click
    rv = run(action)
  File "/Users/rayansoussi/Desktop/renpy-8.3.4-sdk/renpy/display/behavior.py", line 401, in run
    return action(*args, **kwargs)
  File "renpy/common/00action_menu.rpy", line 274, in __call__
    renpy.quit(save=True)
  File "/Users/rayansoussi/Desktop/renpy-8.3.4-sdk/renpy/exports/restartexports.py", line 135, in quit
    raise renpy.game.QuitException(relaunch=relaunch, status=status)
renpy.game.QuitException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/rayansoussi/Desktop/renpy-8.3.4-sdk/renpy/bootstrap.py", line 359, in bootstrap
    renpy.main.main()
  File "/Users/rayansoussi/Desktop/renpy-8.3.4-sdk/renpy/main.py", line 666, in main
    renpy.persistent.update(True)
  File "/Users/rayansoussi/Desktop/renpy-8.3.4-sdk/renpy/persistent.py", line 434, in update
    save()
  File "/Users/rayansoussi/Desktop/renpy-8.3.4-sdk/renpy/persistent.py", line 456, in save
    renpy.loadsave.location.save_persistent(compressed)
  File "/Users/rayansoussi/Desktop/renpy-8.3.4-sdk/renpy/savelocation.py", line 622, in save_persistent
    l.save_persistent(data)
  File "/Users/rayansoussi/Desktop/renpy-8.3.4-sdk/renpy/savelocation.py", line 426, in save_persistent
    with open(fn_tmp, "wb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/rayansoussi/Desktop/renpy-8.3.4-sdk/JustAnotherNight/game/saves/persistent.1736601646.tmp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/rayansoussi/Desktop/renpy-8.3.4-sdk/renpy/editor.py", line 171, in launch_editor
    editor.end()
  File "/Users/rayansoussi/Desktop/renpy-8.3.4-sdk/launcher/Visual Studio Code (System).edit.py", line 79, in end
    subprocess.Popen(args)
  File "lib/python3.9/subprocess.py", line 951, in __init__
  File "lib/python3.9/subprocess.py", line 1821, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'code'
